//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 12:31:28 AM EEST 
//


package lab3.enterprise_yutsyk;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for activity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="activity">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Легка промисловість"/>
 *     &lt;enumeration value="Машинобудування"/>
 *     &lt;enumeration value="Продаж авто"/>
 *     &lt;enumeration value="IT"/>
 *     &lt;enumeration value="GameDev"/>
 *     &lt;enumeration value="Продаж продуктів"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "activity")
@XmlEnum
public enum Activity {

    @XmlEnumValue("\u041b\u0435\u0433\u043a\u0430 \u043f\u0440\u043e\u043c\u0438\u0441\u043b\u043e\u0432\u0456\u0441\u0442\u044c")
    ЛЕГКА_ПРОМИСЛОВІСТЬ("\u041b\u0435\u0433\u043a\u0430 \u043f\u0440\u043e\u043c\u0438\u0441\u043b\u043e\u0432\u0456\u0441\u0442\u044c"),
    @XmlEnumValue("\u041c\u0430\u0448\u0438\u043d\u043e\u0431\u0443\u0434\u0443\u0432\u0430\u043d\u043d\u044f")
    МАШИНОБУДУВАННЯ("\u041c\u0430\u0448\u0438\u043d\u043e\u0431\u0443\u0434\u0443\u0432\u0430\u043d\u043d\u044f"),
    @XmlEnumValue("\u041f\u0440\u043e\u0434\u0430\u0436 \u0430\u0432\u0442\u043e")
    ПРОДАЖ_АВТО("\u041f\u0440\u043e\u0434\u0430\u0436 \u0430\u0432\u0442\u043e"),
    IT("IT"),
    @XmlEnumValue("GameDev")
    GAME_DEV("GameDev"),
    @XmlEnumValue("\u041f\u0440\u043e\u0434\u0430\u0436 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0456\u0432")
    ПРОДАЖ_ПРОДУКТІВ("\u041f\u0440\u043e\u0434\u0430\u0436 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0456\u0432");
    private final String value;

    Activity(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Activity fromValue(String v) {
        for (Activity c: Activity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
