//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 12:31:28 AM EEST 
//


package lab3.enterprise_yutsyk;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lab3.enterprise_yutsyk package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lab3.enterprise_yutsyk
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateEnterpriseRequest }
     * 
     */
    public CreateEnterpriseRequest createCreateEnterpriseRequest() {
        return new CreateEnterpriseRequest();
    }

    /**
     * Create an instance of {@link Enterprise }
     * 
     */
    public Enterprise createEnterprise() {
        return new Enterprise();
    }

    /**
     * Create an instance of {@link GetEnterprisesByNameStartedWithRequest }
     * 
     */
    public GetEnterprisesByNameStartedWithRequest createGetEnterprisesByNameStartedWithRequest() {
        return new GetEnterprisesByNameStartedWithRequest();
    }

    /**
     * Create an instance of {@link GetEnterprisesByFounderRequest }
     * 
     */
    public GetEnterprisesByFounderRequest createGetEnterprisesByFounderRequest() {
        return new GetEnterprisesByFounderRequest();
    }

    /**
     * Create an instance of {@link GetEnterpriseByNameRequest }
     * 
     */
    public GetEnterpriseByNameRequest createGetEnterpriseByNameRequest() {
        return new GetEnterpriseByNameRequest();
    }

    /**
     * Create an instance of {@link GetEnterpriseByNameRespond }
     * 
     */
    public GetEnterpriseByNameRespond createGetEnterpriseByNameRespond() {
        return new GetEnterpriseByNameRespond();
    }

    /**
     * Create an instance of {@link UpdateEnterpriseRequest }
     * 
     */
    public UpdateEnterpriseRequest createUpdateEnterpriseRequest() {
        return new UpdateEnterpriseRequest();
    }

    /**
     * Create an instance of {@link DeleteEnterpriseRequest }
     * 
     */
    public DeleteEnterpriseRequest createDeleteEnterpriseRequest() {
        return new DeleteEnterpriseRequest();
    }

    /**
     * Create an instance of {@link GetEnterprisesRequest }
     * 
     */
    public GetEnterprisesRequest createGetEnterprisesRequest() {
        return new GetEnterprisesRequest();
    }

    /**
     * Create an instance of {@link GetEnterprisesRespond }
     * 
     */
    public GetEnterprisesRespond createGetEnterprisesRespond() {
        return new GetEnterprisesRespond();
    }

}
