//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 12:31:28 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://enterprise-yutsyk.lab3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lab3.enterprise_yutsyk;
